name: Update docs

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: docs
    - name: Build & Publish
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        ls
        rm -r docs
        rm -r repo
        rm .gitmodules
        ls
        git add . && git commit -m "Removing old files" 
        git config user.name dubisdev
        git config user.email dubisdev@gmail.com
        yarn publicar
