name: Update docs

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * *
    
jobs:
  generateDocsWebpage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: docs
        token: ${{ secrets.GH_TOKEN }}
        
    - name: Use Node.js version 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Configure Git Username
      run: |
        git config user.name dubisdev
        git config user.email dubisdev@gmail.com
        
    - name: Delete old files
      run: |
        ls
        rm -r docs
        rm -r repo
        rm .gitmodules
        ls
        
        git add .
        git commit -m "Removing old files"
    
    - name: Submodule Docs Repo
      run: |
        git submodule add --force https://github.com/dubisdev/todoist-rest-client-documentation repo
        git submodule update --remote -f
        
    - name: Build docs website
      run: |
        cd repo
        yarn
        yarn build
      
    - name: Copy repo/build to docs folder
      run: |
        mkdir docs
        ls
        cp -a repo/build/. docs/
        
    - name: Save changes on the repo
      run: |
        git add .
        git commit -m "Updating docs"
        git push
        
