name: Run Tests

on: [pull_request]

jobs:
  run_tests:
    name: Run Node Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Installing project dependencies
        run: yarn
      - name: Running tests
        run: yarn test
        env:
          TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}

  generateCoverage:
    name: Upload Coverage to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
